/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'staff-users': StaffUserAuthOperations;
  };
  blocks: {};
  collections: {
    'staff-users': StaffUser;
    media: Media;
    'audit-log': AuditLog;
    'invite-tokens': InviteToken;
    'onboarding-packs': OnboardingPack;
    'onboarding-assignments': OnboardingAssignment;
    'onboarding-tasks': OnboardingTask;
    'onboarding-documents': OnboardingDocument;
    'onboarding-events': OnboardingEvent;
    'onboarding-overrides': OnboardingOverride;
    'time-entries': TimeEntry;
    'shift-notes': ShiftNote;
    'time-entry-corrections': TimeEntryCorrection;
    'survey-templates': SurveyTemplate;
    'survey-assignments': SurveyAssignment;
    'survey-responses': SurveyResponse;
    'survey-response-drafts': SurveyResponseDraft;
    'session-contact-details': SessionContactDetail;
    contracts: Contract;
    'contract-signing-drafts': ContractSigningDraft;
    'contract-signatures': ContractSignature;
    'training-modules': TrainingModule;
    'training-completions': TrainingCompletion;
    incidents: Incident;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'staff-users': StaffUsersSelect<false> | StaffUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'invite-tokens': InviteTokensSelect<false> | InviteTokensSelect<true>;
    'onboarding-packs': OnboardingPacksSelect<false> | OnboardingPacksSelect<true>;
    'onboarding-assignments': OnboardingAssignmentsSelect<false> | OnboardingAssignmentsSelect<true>;
    'onboarding-tasks': OnboardingTasksSelect<false> | OnboardingTasksSelect<true>;
    'onboarding-documents': OnboardingDocumentsSelect<false> | OnboardingDocumentsSelect<true>;
    'onboarding-events': OnboardingEventsSelect<false> | OnboardingEventsSelect<true>;
    'onboarding-overrides': OnboardingOverridesSelect<false> | OnboardingOverridesSelect<true>;
    'time-entries': TimeEntriesSelect<false> | TimeEntriesSelect<true>;
    'shift-notes': ShiftNotesSelect<false> | ShiftNotesSelect<true>;
    'time-entry-corrections': TimeEntryCorrectionsSelect<false> | TimeEntryCorrectionsSelect<true>;
    'survey-templates': SurveyTemplatesSelect<false> | SurveyTemplatesSelect<true>;
    'survey-assignments': SurveyAssignmentsSelect<false> | SurveyAssignmentsSelect<true>;
    'survey-responses': SurveyResponsesSelect<false> | SurveyResponsesSelect<true>;
    'survey-response-drafts': SurveyResponseDraftsSelect<false> | SurveyResponseDraftsSelect<true>;
    'session-contact-details': SessionContactDetailsSelect<false> | SessionContactDetailsSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    'contract-signing-drafts': ContractSigningDraftsSelect<false> | ContractSigningDraftsSelect<true>;
    'contract-signatures': ContractSignaturesSelect<false> | ContractSignaturesSelect<true>;
    'training-modules': TrainingModulesSelect<false> | TrainingModulesSelect<true>;
    'training-completions': TrainingCompletionsSelect<false> | TrainingCompletionsSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'org-settings': OrgSetting;
  };
  globalsSelect: {
    'org-settings': OrgSettingsSelect<false> | OrgSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    'staff-hub-command': StaffHubCommandWidget;
    collections: CollectionsWidget;
  };
  user: StaffUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff and contractor accounts for the portal
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-users".
 */
export interface StaffUser {
  id: number;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  role: 'admin' | 'manager' | 'staff' | 'contractor';
  employmentType?: ('employee' | 'contractor') | null;
  manager?: (number | null) | StaffUser;
  /**
   * Account access. Active unlocks the full staff portal. Inactive blocks portal access.
   */
  status?: ('active' | 'invited' | 'inactive') | null;
  /**
   * Employee onboarding progress. Usually set automatically via review approval; admins can override here.
   */
  onboardingStatus?:
    | (
        | 'invited'
        | 'in_progress'
        | 'submitted'
        | 'pending_admin_review'
        | 'approved'
        | 'active'
        | 'rejected'
        | 'suspended'
      )
    | null;
  startDate?: string | null;
  jobProfile?: ('field_worker' | 'office_admin' | 'co_design_facilitator') | null;
  contactDataViewer?: boolean | null;
  employmentBasis?: ('full_time' | 'part_time' | 'casual' | 'fixed_term') | null;
  profile?: {
    title?: ('Mr' | 'Mrs' | 'Miss' | 'Ms') | null;
    dateOfBirth?: string | null;
    mobile?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    suburb?: string | null;
    state?: string | null;
    postcode?: string | null;
    otherGivenNames?: string | null;
    emergencyContactName?: string | null;
    emergencyContactPhone?: string | null;
    emergencyContactRelationship?: string | null;
  };
  /**
   * Payroll employee number used on NAT 13080 and downstream payroll systems.
   */
  employeeNumber?: string | null;
  /**
   * Captured for onboarding form submission and encrypted in bankEncrypted.
   */
  bankAccountName?: string | null;
  /**
   * Captured for onboarding form submission and encrypted in bankEncrypted.
   */
  bankBsb?: string | null;
  /**
   * Captured for onboarding form submission and encrypted in bankEncrypted.
   */
  bankAccountNumber?: string | null;
  bankAccountMasked?: string | null;
  bankEncrypted?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Transient entry field only. Value is encrypted into tfnEncrypted and not stored in plain text.
   */
  tfn?: string | null;
  tfnMasked?: string | null;
  tfnEncrypted?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Structured tax declarations captured from onboarding TaxTask.
   */
  taxDeclaration?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taxSetupStatus?: ('not_started' | 'employee_confirmed' | 'verified_in_xero' | 'admin_override') | null;
  /**
   * Structured super choice details captured from onboarding SuperTask.
   */
  superChoiceData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  superChoiceStatus?: ('not_started' | 'submitted' | 'verified') | null;
  superChoiceDueDate?: string | null;
  /**
   * Superannuation fund or provider name from onboarding.
   */
  superFundName?: string | null;
  /**
   * Superannuation fund ID (USI or ABN) from onboarding.
   */
  superFundId?: string | null;
  /**
   * Super fund member number from onboarding.
   */
  superMemberNumber?: string | null;
  /**
   * Employee elected to use the employer default super fund.
   */
  superUseDefaultFund?: boolean | null;
  /**
   * Letter of compliance from the employee super fund (required when nominating an existing fund).
   */
  superComplianceLetter?: (number | null) | Media;
  /**
   * Vault document record linked to the super fund compliance letter upload.
   */
  superComplianceLetterDocument?: (number | null) | OnboardingDocument;
  awardName?: string | null;
  classificationLevel?: string | null;
  baseHourlyRate?: number | null;
  casualLoading?: number | null;
  rtwStatus?: ('not_started' | 'submitted' | 'verified' | 'rejected') | null;
  citizenshipPath?: ('australian_citizen' | 'permanent_resident' | 'visa_holder') | null;
  visaSubclass?: string | null;
  workRightsExpiry?: string | null;
  ndisClearanceId?: string | null;
  wwccNumber?: string | null;
  xeroEmployeeId?: string | null;
  xeroSyncedAt?: string | null;
  xeroSyncStatus?: ('not_synced' | 'pending' | 'synced' | 'error') | null;
  xeroSyncError?: string | null;
  /**
   * For contractors — auto-deactivate after co-design project
   */
  expiresAt?: string | null;
  totpEnabled?: boolean | null;
  totpSecret?: string | null;
  recoveryCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * NDIS worker screening expiry (optional)
   */
  workerScreeningExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'staff-users';
}
/**
 * PDFs, images, and contract document uploads
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  classification?: ('general' | 'contract' | 'incident' | 'onboarding_pii') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Vault documents generated or uploaded during onboarding
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-documents".
 */
export interface OnboardingDocument {
  id: number;
  user: number | StaffUser;
  assignment?: (number | null) | OnboardingAssignment;
  task?: (number | null) | OnboardingTask;
  title: string;
  documentType?:
    | (
        | 'contract_signed'
        | 'fwis_ack'
        | 'super_choice'
        | 'tax_setup'
        | 'compliance'
        | 'payroll_packet'
        | 'onboarding_packet'
      )
    | null;
  media?: (number | null) | Media;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  issuedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-user onboarding snapshot frozen at invite acceptance
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-assignments".
 */
export interface OnboardingAssignment {
  id: number;
  user: number | StaffUser;
  pack: number | OnboardingPack;
  packVersion: number;
  assignedContracts?: (number | Contract)[] | null;
  assignedTraining?: (number | TrainingModule)[] | null;
  assignedPolicies?: (number | TrainingModule)[] | null;
  assignedSurveys?: (number | SurveyTemplate)[] | null;
  complianceChecks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startDate?: string | null;
  manager?: (number | null) | StaffUser;
  status?: ('in_progress' | 'submitted' | 'pending_admin_review' | 'approved' | 'rejected') | null;
  submittedAt?: string | null;
  reviewedAt?: string | null;
  reviewer?: (number | null) | StaffUser;
  reviewLockAt?: string | null;
  reviewNotes?: string | null;
  stapledSuperReviewRequired?: boolean | null;
  xeroSyncStatus?: ('not_started' | 'pending' | 'synced' | 'failed') | null;
  xeroSyncAt?: string | null;
  xeroSyncError?: string | null;
  onboardingTasks?: (number | OnboardingTask)[] | null;
  superChoiceDueDate?: string | null;
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Role-based onboarding templates assigned during invite
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-packs".
 */
export interface OnboardingPack {
  id: number;
  name: string;
  /**
   * Public join link: /onboard/{slug} (pack must be active)
   */
  slug: string;
  description?: string | null;
  portalRoles: ('staff' | 'manager')[];
  jobProfile?: ('field_worker' | 'office_admin' | 'co_design_facilitator') | null;
  employmentBasis?: ('full_time' | 'part_time' | 'casual' | 'fixed_term')[] | null;
  contracts?: (number | Contract)[] | null;
  trainingModules?: (number | TrainingModule)[] | null;
  policyModules?: (number | TrainingModule)[] | null;
  surveyTemplates?: (number | SurveyTemplate)[] | null;
  complianceChecks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workState?: ('ACT' | 'NSW' | 'NT' | 'QLD' | 'SA' | 'TAS' | 'VIC' | 'WA') | null;
  estimatedMinutes?: number | null;
  version: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Employment agreements and PDF templates for staff to sign
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: number;
  title: string;
  /**
   * Summary shown in the portal if no PDFs are attached. Optional when document PDFs are uploaded.
   */
  bodyText?: string | null;
  version: number;
  /**
   * PDF documents merged in upload order (e.g. employment award + position description). Staff receive one combined printable PDF after signing.
   */
  documentPdfs?: (number | Media)[] | null;
  /**
   * Legacy single PDF — use Document PDFs for multiple files.
   */
  templatePdf?: (number | null) | Media;
  applicableRoles?: ('staff' | 'contractor' | 'manager')[] | null;
  required?: boolean | null;
  effectiveFrom?: string | null;
  /**
   * JSON array of form fields staff complete before signing. Same shape as surveys: { id, type, label, required?, options?, step? }. Leave empty to use the default staff contract form.
   */
  formFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Maps form field ids to PDF AcroForm field names, e.g. { "firstName": "FirstName" }. Used when document PDFs contain fillable fields.
   */
  pdfFieldMap?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  useDefaultForm?: boolean | null;
  /**
   * When enabled and Didit API keys are configured, staff must complete biometric verification between entering details and signing.
   */
  requireDiditVerification?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Training induction and policy & procedure modules for staff onboarding
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-modules".
 */
export interface TrainingModule {
  id: number;
  /**
   * Training appears under Training; policy & procedure under Policies in the staff portal.
   */
  moduleType: 'training' | 'policy_procedure';
  title: string;
  slug: string;
  content: string;
  /**
   * One-line hook shown on module card
   */
  summary?: string | null;
  /**
   * Optional override for displayed duration (~N min). Auto-calculated from content blocks when empty.
   */
  estimatedMinutes?: number | null;
  /**
   * Structured screens: [{ id, type, title?, body?, videoUrl?, transcript?, durationMinutes?, resourceUrl?, resourceTitle?, resourceKind?, downloadable?, attribution?, checklist?, quiz?, attestationLabel? }]
   */
  contentBlocks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Session Capture form version this module aligns to (e.g. 2.0)
   */
  linkedFormVersion?: string | null;
  /**
   * Optional quiz: { passScore, questions: [{ id, prompt, options: [{ id, label, correct? }] }] }
   */
  quizDefinition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requiresScenarioGate?: boolean | null;
  requiredForRoles?: ('staff' | 'contractor' | 'manager')[] | null;
  sortOrder?: number | null;
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable survey forms and question definitions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-templates".
 */
export interface SurveyTemplate {
  id: number;
  /**
   * Stable identifier e.g. session-capture-v2-live
   */
  slug?: string | null;
  title: string;
  formKind?: ('general' | 'session_capture') | null;
  captureMode?: ('live' | 'practice') | null;
  formVersion?: string | null;
  description?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * JSON array: { id, type, label, required?, options?, step?, showWhen?, fieldRole?, scriptText? }. Types include script, section for session capture.
   */
  fields:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  version?: number | null;
  piiWarning?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Materialized per-user onboarding checklist rows
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-tasks".
 */
export interface OnboardingTask {
  id: number;
  user: number | StaffUser;
  assignment: number | OnboardingAssignment;
  title: string;
  group: 'before_work' | 'before_pay' | 'compliance' | 'reference';
  type:
    | 'contract'
    | 'training'
    | 'policy'
    | 'survey'
    | 'profile'
    | 'bank'
    | 'tax'
    | 'super'
    | 'fwis'
    | 'rtw'
    | 'compliance'
    | 'manual';
  status?: ('pending' | 'in_progress' | 'awaiting_review' | 'complete' | 'rejected' | 'blocked') | null;
  blocks?: ('canWork' | 'canBePaid' | 'canWorkUnsupervised')[] | null;
  referenceCollection?: string | null;
  referenceId?: string | null;
  href?: string | null;
  notes?: string | null;
  dueDate?: string | null;
  completedAt?: string | null;
  completedBy?: (number | null) | StaffUser;
  reviewedAt?: string | null;
  reviewedBy?: (number | null) | StaffUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * System-wide activity log for compliance and troubleshooting
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | StaffUser;
  action: string;
  resourceType: string;
  resourceId?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pending and sent portal invitation links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-tokens".
 */
export interface InviteToken {
  id: number;
  email: string;
  tokenHash: string;
  role: 'staff' | 'manager';
  pack?: (number | null) | OnboardingPack;
  assignedContractIds?: (number | Contract)[] | null;
  assignedTrainingIds?: (number | TrainingModule)[] | null;
  assignedPolicyIds?: (number | TrainingModule)[] | null;
  assignedSurveyIds?: (number | SurveyTemplate)[] | null;
  jobProfile?: ('field_worker' | 'office_admin' | 'co_design_facilitator') | null;
  employeeNumber?: string | null;
  employmentBasis?: ('full_time' | 'part_time' | 'casual' | 'fixed_term') | null;
  manager?: (number | null) | StaffUser;
  startDate?: string | null;
  complianceChecks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable audit stream for onboarding workflow transitions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-events".
 */
export interface OnboardingEvent {
  id: number;
  user: number | StaffUser;
  assignment?: (number | null) | OnboardingAssignment;
  task?: (number | null) | OnboardingTask;
  eventType:
    | 'pack_assigned'
    | 'task_completed'
    | 'contract_signed'
    | 'training_completed'
    | 'submitted'
    | 'approved'
    | 'rejected'
    | 'resubmitted'
    | 'override_granted'
    | 'compliance_expired'
    | 'payroll_packet_exported'
    | 'forms_verified'
    | 'xero_sync_queued'
    | 'xero_sync_completed'
    | 'xero_sync_failed';
  actor?: (number | null) | StaffUser;
  note?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Temporary admin exceptions for clock-in and payroll gates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-overrides".
 */
export interface OnboardingOverride {
  id: number;
  user: number | StaffUser;
  reason: string;
  allowsClockIn?: boolean | null;
  allowsPayroll?: boolean | null;
  expiresAt: string;
  grantedBy: number | StaffUser;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Raw clock-in and clock-out records. For approvals, use Time Approvals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries".
 */
export interface TimeEntry {
  id: number;
  user: number | StaffUser;
  clockIn: string;
  clockOut?: string | null;
  breakMinutes?: number | null;
  projectTag: string;
  status?: ('active' | 'submitted' | 'approved' | 'rejected') | null;
  approvedBy?: (number | null) | StaffUser;
  approvedAt?: string | null;
  approvalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Notes attached to individual time entries
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shift-notes".
 */
export interface ShiftNote {
  id: number;
  timeEntry: number | TimeEntry;
  activitiesDone: string;
  achievements?: string | null;
  blockers?: string | null;
  freeText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only correction history for Fair Work compliance
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entry-corrections".
 */
export interface TimeEntryCorrection {
  id: number;
  timeEntry: number | TimeEntry;
  correctedBy: number | StaffUser;
  reason: string;
  previousValues:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  newValues:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Surveys assigned to staff with due dates and status
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-assignments".
 */
export interface SurveyAssignment {
  id: number;
  template: number | SurveyTemplate;
  assignee: number | StaffUser;
  dueDate?: string | null;
  status?: ('pending' | 'in_progress' | 'complete') | null;
  /**
   * Optional label e.g. Mock Module 16 or session date
   */
  sessionLabel?: string | null;
  timeEntry?: (number | null) | TimeEntry;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submitted survey answers from staff members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-responses".
 */
export interface SurveyResponse {
  id: number;
  assignment: number | SurveyAssignment;
  template: number | SurveyTemplate;
  respondent: number | StaffUser;
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt: string;
  timeEntry?: (number | null) | TimeEntry;
  captureMode?: ('live' | 'practice') | null;
  piiFlags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attestations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  formVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-progress session captures and surveys
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-response-drafts".
 */
export interface SurveyResponseDraft {
  id: number;
  assignment: number | SurveyAssignment;
  respondent: number | StaffUser;
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  currentStep?: number | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Section 8 contact PII — separated from session research capture
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-contact-details".
 */
export interface SessionContactDetail {
  id: number;
  sessionResponse: number | SurveyResponse;
  facilitator: number | StaffUser;
  contactAnswers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt: string;
  formVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-progress contract signings awaiting identity verification
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-signing-drafts".
 */
export interface ContractSigningDraft {
  id: number;
  user: number | StaffUser;
  contract: number | Contract;
  formResponses:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  diditSessionId?: string | null;
  verificationStatus?: ('pending' | 'approved' | 'declined' | 'expired') | null;
  /**
   * Didit decision payload when verification completes.
   */
  diditVerification?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt?: string | null;
  /**
   * When the employee confirmed their onboarding summary before signing.
   */
  onboardingConfirmedAt?: string | null;
  /**
   * Frozen copy of the onboarding summary shown at confirmation.
   */
  onboardingSummarySnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Completed contract signatures with audit trail
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-signatures".
 */
export interface ContractSignature {
  id: number;
  user: number | StaffUser;
  contract: number | Contract;
  contractVersion: number;
  documentHash: string;
  signatureMethod?: ('draw' | 'type') | null;
  signatureImage?: (number | null) | Media;
  signedPdf?: (number | null) | Media;
  signedAt: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  consentVersion: string;
  consentTimestamp?: string | null;
  /**
   * Details entered by the signer before signing.
   */
  formResponses?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  signingDraft?: (number | null) | ContractSigningDraft;
  diditSessionId?: string | null;
  diditVerification?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  onboardingConfirmedAt?: string | null;
  /**
   * Onboarding summary confirmed by the employee before signing.
   */
  onboardingSummarySnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff progress and completion records for training modules
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-completions".
 */
export interface TrainingCompletion {
  id: number;
  user: number | StaffUser;
  module: number | TrainingModule;
  completedAt: string;
  moduleVersion?: number | null;
  contentHash?: string | null;
  quizScore?: number | null;
  attemptCount?: number | null;
  /**
   * Stored quiz scenario answers
   */
  responses?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  linkedSurveyResponseId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff-reported safety and compliance incidents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: number;
  reporter: number | StaffUser;
  occurredAt: string;
  location: string;
  category: 'injury' | 'near_miss' | 'property' | 'psychosocial' | 'other';
  description: string;
  witnesses?:
    | {
        name?: string | null;
        contact?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  immediateActions?: string | null;
  treatmentRequired?: boolean | null;
  severity?: ('low' | 'medium' | 'high') | null;
  status?: ('draft' | 'submitted' | 'under_review' | 'closed') | null;
  attachments?: (number | Media)[] | null;
  piiAcknowledged?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'staff-users';
        value: number | StaffUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'invite-tokens';
        value: number | InviteToken;
      } | null)
    | ({
        relationTo: 'onboarding-packs';
        value: number | OnboardingPack;
      } | null)
    | ({
        relationTo: 'onboarding-assignments';
        value: number | OnboardingAssignment;
      } | null)
    | ({
        relationTo: 'onboarding-tasks';
        value: number | OnboardingTask;
      } | null)
    | ({
        relationTo: 'onboarding-documents';
        value: number | OnboardingDocument;
      } | null)
    | ({
        relationTo: 'onboarding-events';
        value: number | OnboardingEvent;
      } | null)
    | ({
        relationTo: 'onboarding-overrides';
        value: number | OnboardingOverride;
      } | null)
    | ({
        relationTo: 'time-entries';
        value: number | TimeEntry;
      } | null)
    | ({
        relationTo: 'shift-notes';
        value: number | ShiftNote;
      } | null)
    | ({
        relationTo: 'time-entry-corrections';
        value: number | TimeEntryCorrection;
      } | null)
    | ({
        relationTo: 'survey-templates';
        value: number | SurveyTemplate;
      } | null)
    | ({
        relationTo: 'survey-assignments';
        value: number | SurveyAssignment;
      } | null)
    | ({
        relationTo: 'survey-responses';
        value: number | SurveyResponse;
      } | null)
    | ({
        relationTo: 'survey-response-drafts';
        value: number | SurveyResponseDraft;
      } | null)
    | ({
        relationTo: 'session-contact-details';
        value: number | SessionContactDetail;
      } | null)
    | ({
        relationTo: 'contracts';
        value: number | Contract;
      } | null)
    | ({
        relationTo: 'contract-signing-drafts';
        value: number | ContractSigningDraft;
      } | null)
    | ({
        relationTo: 'contract-signatures';
        value: number | ContractSignature;
      } | null)
    | ({
        relationTo: 'training-modules';
        value: number | TrainingModule;
      } | null)
    | ({
        relationTo: 'training-completions';
        value: number | TrainingCompletion;
      } | null)
    | ({
        relationTo: 'incidents';
        value: number | Incident;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'staff-users';
    value: number | StaffUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'staff-users';
    value: number | StaffUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-users_select".
 */
export interface StaffUsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  fullName?: T;
  role?: T;
  employmentType?: T;
  manager?: T;
  status?: T;
  onboardingStatus?: T;
  startDate?: T;
  jobProfile?: T;
  contactDataViewer?: T;
  employmentBasis?: T;
  profile?:
    | T
    | {
        title?: T;
        dateOfBirth?: T;
        mobile?: T;
        addressLine1?: T;
        addressLine2?: T;
        suburb?: T;
        state?: T;
        postcode?: T;
        otherGivenNames?: T;
        emergencyContactName?: T;
        emergencyContactPhone?: T;
        emergencyContactRelationship?: T;
      };
  employeeNumber?: T;
  bankAccountName?: T;
  bankBsb?: T;
  bankAccountNumber?: T;
  bankAccountMasked?: T;
  bankEncrypted?: T;
  tfn?: T;
  tfnMasked?: T;
  tfnEncrypted?: T;
  taxDeclaration?: T;
  taxSetupStatus?: T;
  superChoiceData?: T;
  superChoiceStatus?: T;
  superChoiceDueDate?: T;
  superFundName?: T;
  superFundId?: T;
  superMemberNumber?: T;
  superUseDefaultFund?: T;
  superComplianceLetter?: T;
  superComplianceLetterDocument?: T;
  awardName?: T;
  classificationLevel?: T;
  baseHourlyRate?: T;
  casualLoading?: T;
  rtwStatus?: T;
  citizenshipPath?: T;
  visaSubclass?: T;
  workRightsExpiry?: T;
  ndisClearanceId?: T;
  wwccNumber?: T;
  xeroEmployeeId?: T;
  xeroSyncedAt?: T;
  xeroSyncStatus?: T;
  xeroSyncError?: T;
  expiresAt?: T;
  totpEnabled?: T;
  totpSecret?: T;
  recoveryCodes?: T;
  workerScreeningExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  classification?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  resourceType?: T;
  resourceId?: T;
  ipAddress?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-tokens_select".
 */
export interface InviteTokensSelect<T extends boolean = true> {
  email?: T;
  tokenHash?: T;
  role?: T;
  pack?: T;
  assignedContractIds?: T;
  assignedTrainingIds?: T;
  assignedPolicyIds?: T;
  assignedSurveyIds?: T;
  jobProfile?: T;
  employeeNumber?: T;
  employmentBasis?: T;
  manager?: T;
  startDate?: T;
  complianceChecks?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-packs_select".
 */
export interface OnboardingPacksSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  portalRoles?: T;
  jobProfile?: T;
  employmentBasis?: T;
  contracts?: T;
  trainingModules?: T;
  policyModules?: T;
  surveyTemplates?: T;
  complianceChecks?: T;
  workState?: T;
  estimatedMinutes?: T;
  version?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-assignments_select".
 */
export interface OnboardingAssignmentsSelect<T extends boolean = true> {
  user?: T;
  pack?: T;
  packVersion?: T;
  assignedContracts?: T;
  assignedTraining?: T;
  assignedPolicies?: T;
  assignedSurveys?: T;
  complianceChecks?: T;
  startDate?: T;
  manager?: T;
  status?: T;
  submittedAt?: T;
  reviewedAt?: T;
  reviewer?: T;
  reviewLockAt?: T;
  reviewNotes?: T;
  stapledSuperReviewRequired?: T;
  xeroSyncStatus?: T;
  xeroSyncAt?: T;
  xeroSyncError?: T;
  onboardingTasks?: T;
  superChoiceDueDate?: T;
  snapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-tasks_select".
 */
export interface OnboardingTasksSelect<T extends boolean = true> {
  user?: T;
  assignment?: T;
  title?: T;
  group?: T;
  type?: T;
  status?: T;
  blocks?: T;
  referenceCollection?: T;
  referenceId?: T;
  href?: T;
  notes?: T;
  dueDate?: T;
  completedAt?: T;
  completedBy?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-documents_select".
 */
export interface OnboardingDocumentsSelect<T extends boolean = true> {
  user?: T;
  assignment?: T;
  task?: T;
  title?: T;
  documentType?: T;
  media?: T;
  metadata?: T;
  issuedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-events_select".
 */
export interface OnboardingEventsSelect<T extends boolean = true> {
  user?: T;
  assignment?: T;
  task?: T;
  eventType?: T;
  actor?: T;
  note?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-overrides_select".
 */
export interface OnboardingOverridesSelect<T extends boolean = true> {
  user?: T;
  reason?: T;
  allowsClockIn?: T;
  allowsPayroll?: T;
  expiresAt?: T;
  grantedBy?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entries_select".
 */
export interface TimeEntriesSelect<T extends boolean = true> {
  user?: T;
  clockIn?: T;
  clockOut?: T;
  breakMinutes?: T;
  projectTag?: T;
  status?: T;
  approvedBy?: T;
  approvedAt?: T;
  approvalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shift-notes_select".
 */
export interface ShiftNotesSelect<T extends boolean = true> {
  timeEntry?: T;
  activitiesDone?: T;
  achievements?: T;
  blockers?: T;
  freeText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-entry-corrections_select".
 */
export interface TimeEntryCorrectionsSelect<T extends boolean = true> {
  timeEntry?: T;
  correctedBy?: T;
  reason?: T;
  previousValues?: T;
  newValues?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-templates_select".
 */
export interface SurveyTemplatesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  formKind?: T;
  captureMode?: T;
  formVersion?: T;
  description?: T;
  status?: T;
  fields?: T;
  version?: T;
  piiWarning?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-assignments_select".
 */
export interface SurveyAssignmentsSelect<T extends boolean = true> {
  template?: T;
  assignee?: T;
  dueDate?: T;
  status?: T;
  sessionLabel?: T;
  timeEntry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-responses_select".
 */
export interface SurveyResponsesSelect<T extends boolean = true> {
  assignment?: T;
  template?: T;
  respondent?: T;
  answers?: T;
  submittedAt?: T;
  timeEntry?: T;
  captureMode?: T;
  piiFlags?: T;
  attestations?: T;
  formVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-response-drafts_select".
 */
export interface SurveyResponseDraftsSelect<T extends boolean = true> {
  assignment?: T;
  respondent?: T;
  answers?: T;
  currentStep?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-contact-details_select".
 */
export interface SessionContactDetailsSelect<T extends boolean = true> {
  sessionResponse?: T;
  facilitator?: T;
  contactAnswers?: T;
  submittedAt?: T;
  formVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  title?: T;
  bodyText?: T;
  version?: T;
  documentPdfs?: T;
  templatePdf?: T;
  applicableRoles?: T;
  required?: T;
  effectiveFrom?: T;
  formFields?: T;
  pdfFieldMap?: T;
  useDefaultForm?: T;
  requireDiditVerification?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-signing-drafts_select".
 */
export interface ContractSigningDraftsSelect<T extends boolean = true> {
  user?: T;
  contract?: T;
  formResponses?: T;
  diditSessionId?: T;
  verificationStatus?: T;
  diditVerification?: T;
  expiresAt?: T;
  onboardingConfirmedAt?: T;
  onboardingSummarySnapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-signatures_select".
 */
export interface ContractSignaturesSelect<T extends boolean = true> {
  user?: T;
  contract?: T;
  contractVersion?: T;
  documentHash?: T;
  signatureMethod?: T;
  signatureImage?: T;
  signedPdf?: T;
  signedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  consentVersion?: T;
  consentTimestamp?: T;
  formResponses?: T;
  signingDraft?: T;
  diditSessionId?: T;
  diditVerification?: T;
  onboardingConfirmedAt?: T;
  onboardingSummarySnapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-modules_select".
 */
export interface TrainingModulesSelect<T extends boolean = true> {
  moduleType?: T;
  title?: T;
  slug?: T;
  content?: T;
  summary?: T;
  estimatedMinutes?: T;
  contentBlocks?: T;
  linkedFormVersion?: T;
  quizDefinition?: T;
  requiresScenarioGate?: T;
  requiredForRoles?: T;
  sortOrder?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-completions_select".
 */
export interface TrainingCompletionsSelect<T extends boolean = true> {
  user?: T;
  module?: T;
  completedAt?: T;
  moduleVersion?: T;
  contentHash?: T;
  quizScore?: T;
  attemptCount?: T;
  responses?: T;
  ipAddress?: T;
  userAgent?: T;
  linkedSurveyResponseId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  reporter?: T;
  occurredAt?: T;
  location?: T;
  category?: T;
  description?: T;
  witnesses?:
    | T
    | {
        name?: T;
        contact?: T;
        role?: T;
        id?: T;
      };
  immediateActions?: T;
  treatmentRequired?: T;
  severity?: T;
  status?: T;
  attachments?: T;
  piiAcknowledged?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-settings".
 */
export interface OrgSetting {
  id: number;
  employerLegalName: string;
  employerTradingName?: string | null;
  employerAbn: string;
  employerAddressLine1?: string | null;
  employerAddressLine2?: string | null;
  employerAddressSuburb?: string | null;
  employerAddressState?: string | null;
  employerAddressPostcode?: string | null;
  /**
   * Optional display copy of the registered address; PDF prefill uses the structured address fields above.
   */
  employerBusinessAddress?: string | null;
  payerBranchNumber?: string | null;
  payrollContactName?: string | null;
  payrollContactPhone?: string | null;
  payrollContactEmail?: string | null;
  authorizedSignatoryName?: string | null;
  authorizedSignatoryTitle?: string | null;
  /**
   * Controls whether NAT3093 payer declaration dates (DecPayer-*) are prefilled.
   */
  payerDeclarationDatePolicy?: ('auto' | 'manual') | null;
  payrollSystemName?: string | null;
  defaultSuperFundName: string;
  defaultSuperFundUsi: string;
  defaultSuperFundAbn: string;
  /**
   * Default employment basis used when invites or join flows do not provide one.
   */
  defaultEmploymentBasis: 'full_time' | 'part_time' | 'casual' | 'fixed_term';
  templates: {
    nat3092Version: string;
    nat3093Version: string;
    nat13080Version: string;
    fwisVersion: string;
    ceisVersion: string;
    ftcisVersion: string;
  };
  /**
   * When enabled, super choices are flagged for stapled-super review at approval.
   */
  enableStapledSuperReview?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-settings_select".
 */
export interface OrgSettingsSelect<T extends boolean = true> {
  employerLegalName?: T;
  employerTradingName?: T;
  employerAbn?: T;
  employerAddressLine1?: T;
  employerAddressLine2?: T;
  employerAddressSuburb?: T;
  employerAddressState?: T;
  employerAddressPostcode?: T;
  employerBusinessAddress?: T;
  payerBranchNumber?: T;
  payrollContactName?: T;
  payrollContactPhone?: T;
  payrollContactEmail?: T;
  authorizedSignatoryName?: T;
  authorizedSignatoryTitle?: T;
  payerDeclarationDatePolicy?: T;
  payrollSystemName?: T;
  defaultSuperFundName?: T;
  defaultSuperFundUsi?: T;
  defaultSuperFundAbn?: T;
  defaultEmploymentBasis?: T;
  templates?:
    | T
    | {
        nat3092Version?: T;
        nat3093Version?: T;
        nat13080Version?: T;
        fwisVersion?: T;
        ceisVersion?: T;
        ftcisVersion?: T;
      };
  enableStapledSuperReview?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-hub-command_widget".
 */
export interface StaffHubCommandWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}